# -*- coding: utf-8 -*-
"""데이터과학 10장

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hb6Q8foWQv2GZZE8m9YVRVhYszFmw02Z
"""

import numpy as np

array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('실습 1 : array_a =', array_a)

array_b = np.array(range(10))
print('실습 2 : array_b =', array_b)

array_c = np.array(range(0,10,2))
print('실습 3 : array_c =', array_c)

print('실습 4: ')
print('array_c의 shape :', array_c.shape)
print('array_c의 ndim : ', array_c.ndim)
print('array_c의 ctype :', array_c.dtype)
print('array_c의 size :', array_c.size)
print('array_c의 itemsize :', array_c.itemsize)

import numpy as np

heights = [ 1.83, 1.76, 1.69, 1.86, 1.77, 1.73 ]
weights = [ 86, 74, 59, 95, 80, 68 ]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights/(np_heights**2)
print('대상자들의 키:', np_heights)
print('대상자들의 몸무게:', np_weights)
print('대상자들의 BMI:')
print(bmi)

# LAB 10-3
import numpy as np

x = np.array( [['a', 'b', 'c', 'd'],
               ['c', 'c', 'g', 'h']])
mat_a = np.array( [[10, 20, 30], [10, 20, 30]])
mat_b = np.array( [[2, 2, 2], [1, 2, 3]])

print(x [ x == 'c' ])
print(mat_a - mat_b)

# LAB 10-4
import numpy as np

x = np.array([[ 1.83, 1.76, 1.69, 1.86, 1.77, 1.73 ],
              [ 86.0, 74.0, 59.0, 95.0, 80.0, 68.0 ]])
y = x[0:2, 1:3]
z = x[0:2][1:3]

print('x shape :', x.shape)
print('y shape :', y.shape)
print('z shape :', z.shape)
print('z values = :', z)

bmi = x[1] / x[0]**2
print('BMI data')
print(bmi)

# LAB 10-5
import numpy as np

players = [[170, 76.4],
           [183, 86.2],
           [181, 78.5],
           [176, 80.1]]

np_players = np.array(players)

print('몸무게가 80 이상인 선수 정보')
print(np_players[ np_players[:, 1] >= 80.0 ])

print('키가 180 이상인 선수 정보')
print(np_players[ np_players[:, 0] >= 180.0 ])

# LAB 10-6
import numpy as np

players = np.zeros( (100, 3) )
players[:, 0] = 10 * np.random.randn(100) + 175
players[:, 1] = 10 * np.random.randn(100) + 70
players[:, 2] = np.floor(10 * np.random.randn(100)) + 22

heights = players[:, 0]
print('신장 평균값:', np.mean(heights))
print('신장 중앙값:', np.median(heights))

weights = players[:, 1]
print('체중 평균값:', np.mean(weights))
print('체중 중앙값:', np.median(weights))

ages = players[:, 2]
print('나이 평균값:', np.mean(ages))
print('나이 중앙값:', np.median(ages))

# 심화문제 10.1
import numpy as np

num_arr = np.arange(1, 21)
print(num_arr)

reverse_arr = np.arange(20, 0, -1)
print(reverse_arr)

sum_arr = np.sum(num_arr)
print('num_arr 내의 모든 원소의 합 : ', sum_arr)

num_arr.reshape(5, 4).tolist()

# 심화문제 10.5
import numpy as np

a = np.arange(0, 32).reshape(4, 4, 2)
a1 = a.flatten()

print("10번째 원소 : ", a1[9])
print("20번째 원소 : ", a1[19])